displayitem:
    replacement: '[i]'
    itemformat: '&f[&b%item%&r &ex%amount%&f]&r'
    itemtoolongformat: '&f[&b%item%&f &ex%amount%&f &c(too long)&f]&r'
    
    usebooknameformat: true
    booknameformat: '&o%booktitle%&r'
    
    overridechatformat: false
    format: '&r%displayname%&f: %message%'
    
    spamdetectionbuffer: 5
    spamthreshold: 2000
    jsonlimit: 10000
    listenerpriority: NORMAL
    sendmodifiedchatevent: true
    messages:
        cooldown: '&cPlease wait a few seconds before sharing your item again.'
    