displayitem:
    #set the text shows the 'replacement' string itself in chat instead of the item, to allow posting it in chat - may not contain the replacement string.
    metareplacement: '[I]'
    #set the text that is replaced with the held item - may not contain the meta replacement string
    replacement: '[i]'
    #how the item should appear in chat (using formatting codes and replacements)
    itemformat: '&r[&b%item%&r&e%XamountPL%&f]&r'
    #how the item should appear when it has too many tags to safely display (see jsonlimit)
    itemtoolongformat: '&r[&b%item%&r&e%XamountPL%&f &c(too long)&r]&r'

    #enable or disable book names showing in chat (shows Written Book if disabled)
    usebooknameformat: true
    #how the book name should appear (using formatting codes and replacements)
    booknameformat: '&o%booktitleT%&r'

    #whether to force a particular chat message format or keep the bukkit-event-provided format
    overridechatformat: false
    #how the chat message line should appear (using formatting codes and replacements)
    format: '&r%displayname%&f: %message%'
    
    #how the message shared in chat should appear using bukkit format
    #this is a String.format() compatible string where the username is %1$s and the message is %2$s
    #note that 'overridechatformat' does not affect the share command format, so you must make changes here.
    #note that 'displayitem.replace' permission does not apply to share command uses, it has its own permission.
    #but displayitem.colorname permission does apply to share command appearance.
    shareformatbukkit: "*%1$s %2$s"
    #how a users message sharing an item with /shareitem should appear
    #note that %replacement% should appear somewhere in the message if you want the item to appear at all.
    shareformatmessage: 'shared an item: %replacement%'
    
    

    #how the message shared in chat should appear using bukkit format
    #this is a String.format() compatible string where the username is %1$s and the message is %2$s
    #note that 'overridechatformat' does not affect the share command format, so you must make changes here.
    #note that 'displayitem.replace' permission does not apply to share command uses, it has its own permission.
    #but displayitem.colorname permission does apply to share command appearance.
    shareformatbukkitprivate: "&7&o*%1$s&r &7&o%2$s"
    #how a users message sharing an item with /shareitem should appear
    #note that %replacement% should appear somewhere in the message if you want the item to appear at all.
    shareformatmessageprivate: 'shared an item with you: %replacement%'
    
    
    

    #how many item-display records history to keep for detecting spam
    spamdetectionbuffer: 5
    #sets within how many miliseconds a post in the history is considered spam
    spamthreshold: 2000
    #sets whether a detected spam-post resets the spam timer (each failed post makes the user wait the full duration again) - prior to 2.4.2, the behavior of this was 'true'.
    spamdetectionsresetcooldown: false
    
    #modify items posted in chat to contain less tags
    minimize-items: true
    
    #sets an upper limit on the amount of JSON characters for the item to have a hover component
    jsonlimit: 8000
    #sets the priority at which DisplayItem captures chat messages (lower=before other plugins)
    listenerpriority: NORMAL
    #whether or not to send a ReplacedChatEvent out of courtesy to other plugins
    sendmodifiedchatevent: true
    #whether to block DI's chat events for private /shareitem posts (prevents visibility to plugins like DiscordSRV)
    blockprivatechatevent: true
    
    messages:
        #message displayed to a user when the item-replacement is detected as spam.
        cooldown: '&cPlease wait %cooldownremainderS% seconds before sharing your item again.'
    integrations:
        placeholderapi: true
        
    
