displayitem:
    discordsrv: true
    replacement: '[i]'
    itemformat: '&f[&b%item%&f &ex%amount%&f]&r'
    itemtoolongformat: '&f[&b%item%&f &ex%amount%&f &c(too long)&f]&r'
    spamdetectionbuffer: 5
    spamthreshold: 2000
    jsonlimit: 10000
    messages:
        cooldown: '&cPlease wait a few seconds before sharing your item again.'
    